name: Build LaTeX vedtaegter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "published" ] # Triggers when a release is published

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: fklub-vedtaegter.tex
      - name: Upload PDF document
        uses: actions/upload-artifact@v4
        with:
          name: Vedtaegter
          path: fklub-vedtaegter.pdf

  upload_to_release:
    # This job runs only on release events
    if: github.event_name == 'release'
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Vedtaegter
      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fklub-vedtaegter.pdf
          asset_name: fklub-vedtaegter.pdf
          asset_content_type: application/pdf
